Bhosle_Mahesh _ 02
Apnasite/social-post-assignments pull request #22
Opened 2024-09-18 07:10 UTC by Bhosle07

2024-09-18 17:50 UTC, KalpeshApnasite requested changes

2024-09-18 17:50 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_02/.vscode/settings.json
remove this file

2024-09-18 17:50 UTC, KalpeshApnasite commented on sample-code/preview.html
do not change in sample code

2024-09-20 13:01 UTC, Adarshovhal reviewed
In css file px unit are used.
All classes in the previous.html file.
Background classes in the index.html file.
Code was good in structure.

2024-09-21 05:59 UTC, closed without merging